propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  section:
    _attributes: { phpName: Section }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    name: { phpName: Name, type: VARCHAR, size: '255', required: true }
    sentence: { phpName: Sentence, type: VARCHAR, size: '255', required: true }
